package com.example.animemanager.core.model

fun sampleAnimeSummaries(): List<AnimeSummary> = listOf(
    AnimeSummary(
        id = 1,
        title = "葬送的芙莉莲",
        originalTitle = "葬送のフリーレン",
        seriesStatus = SeriesStatus.ONGOING,
        totalEpisodes = 28,
        updatedEpisodes = 26,
        seasonYear = 2024,
        seasonName = "秋季",
        watchState = WatchState.WATCHING,
        isFavorite = true,
        progressEpisode = 18,
        releaseWeekday = 5,
        releaseMinuteOfDay = 1410,
        scheduleActive = true,
    ),
    AnimeSummary(
        id = 2,
        title = "间谍过家家",
        originalTitle = "SPY x FAMILY",
        seriesStatus = SeriesStatus.FINISHED,
        totalEpisodes = 37,
        updatedEpisodes = 37,
        seasonYear = 2023,
        seasonName = "秋季",
        watchState = WatchState.WATCHED,
        isFavorite = false,
        progressEpisode = 37,
        releaseWeekday = null,
        releaseMinuteOfDay = null,
        scheduleActive = false,
    ),
)

fun sampleAnimeDetail(): AnimeDetail = AnimeDetail(
    id = 1,
    title = "葬送的芙莉莲",
    originalTitle = "葬送のフリーレン",
    synopsis = "在魔王被打倒后的世界里，精灵魔法使芙莉莲继续踏上新的旅程。",
    seriesStatus = SeriesStatus.ONGOING,
    totalEpisodes = 28,
    updatedEpisodes = 26,
    seasonYear = 2024,
    seasonName = "秋季",
    watchState = WatchState.WATCHING,
    isFavorite = true,
    progressEpisode = 18,
    releaseWeekday = 5,
    releaseMinuteOfDay = 1410,
    releaseTimezone = "Asia/Shanghai",
    scheduleActive = true,
    createdAt = 0,
    updatedAt = 0,
)
